import type { CollectionSummary, LibraryCardItem } from "@/components/home/types";

export const mockCollections: CollectionSummary[] = [
  {
    id: "1",
    name: "Magic 151",
    game: "MTG",
    ownedCount: 142,
    totalCount: 165,
    progressPercent: 86,
    gradientFrom: "from-orange-500",
    gradientTo: "to-red-500",
    icon: "🔴",
  },
  {
    id: "2",
    name: "Bloomburrow",
    game: "MTG",
    ownedCount: 88,
    totalCount: 180,
    progressPercent: 49,
    gradientFrom: "from-fuchsia-500",
    gradientTo: "to-purple-600",
    icon: "✨",
  },
  {
    id: "3",
    name: "MTG — Modern Horizons",
    game: "MTG",
    ownedCount: 56,
    totalCount: 303,
    progressPercent: 18,
    gradientFrom: "from-blue-500",
    gradientTo: "to-indigo-600",
    icon: "🌀",
  },
  {
    id: "4",
    name: "Riftbound Origins",
    game: "RiftBound",
    ownedCount: 110,
    totalCount: 195,
    progressPercent: 56,
    gradientFrom: "from-slate-500",
    gradientTo: "to-slate-700",
    icon: "🏆",
  },
  {
    id: "5",
    name: "MTG — Bloomburrow",
    game: "MTG",
    ownedCount: 42,
    totalCount: 261,
    progressPercent: 16,
    gradientFrom: "from-emerald-500",
    gradientTo: "to-teal-600",
    icon: "🍄",
  },
  {
    id: "6",
    name: "Riftbound Legends",
    game: "RiftBound",
    ownedCount: 198,
    totalCount: 258,
    progressPercent: 77,
    gradientFrom: "from-pink-500",
    gradientTo: "to-purple-600",
    icon: "🔮",
  },
  {
    id: "7",
    name: "Constant",
    game: "RiftBound",
    ownedCount: 198,
    totalCount: 258,
    progressPercent: 77,
    gradientFrom: "from-pink-500",
    gradientTo: "to-purple-600",
    icon: "🔮",
  },
];

export const mockLibraryCards: LibraryCardItem[] = [
  {
    id: "1",
    name: "Black Lotus",
    game: "MTG",
    setLabel: "Alpha · 232",
    rarity: "Rare",
    trendPercent: 12.4,
    quantity: 2,
    gradientFrom: "from-zinc-800",
    gradientTo: "to-zinc-900",
    icon: "🪻",
  },
  {
    id: "2",
    name: "Jace, the Mind Sculptor",
    game: "MTG",
    setLabel: "Worldwake · 031",
    rarity: "Mythic",
    trendPercent: 3.1,
    quantity: 1,
    gradientFrom: "from-sky-500",
    gradientTo: "to-blue-600",
    icon: "🧠",
  },
  {
    id: "3",
    name: "The One Ring",
    game: "MTG",
    setLabel: "LTR · 246",
    rarity: "Holo",
    trendPercent: -1.8,
    quantity: 1,
    gradientFrom: "from-yellow-400",
    gradientTo: "to-amber-500",
    icon: "💍",
  },
  {
    id: "4",
    name: "Riftbound Anchor",
    game: "RiftBound",
    setLabel: "Core · 002",
    rarity: "Mythic",
    trendPercent: 5.6,
    quantity: 4,
    gradientFrom: "from-orange-500",
    gradientTo: "to-amber-600",
    icon: "🪝",
  },
  {
    id: "5",
    name: "Photon Dragon",
    game: "MTG",
    setLabel: "Photon · 001",
    rarity: "Secret",
    trendPercent: 8.2,
    quantity: 3,
    gradientFrom: "from-purple-500",
    gradientTo: "to-fuchsia-500",
    icon: "⚔️",
  },
  {
    id: "6",
    name: "Riftbound Vanguard",
    game: "RiftBound",
    setLabel: "Origins · 017",
    rarity: "Secret",
    trendPercent: 8.2,
    quantity: 3,
    gradientFrom: "from-pink-500",
    gradientTo: "to-rose-500",
    icon: "✨",
  },
];